openapi: 3.0.0
info:
  title: projects-api
  version: v4
  description: An OpenAPI definition for the GitLab REST API.
servers:
  - url: 'http://10.177.74.168/api/v4'
paths:
  /projects:
    get:
      tags:
        - projects-api
      parameters:
        - name: archived
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by archived status.
        - name: id_after
          schema:
            type: integer
          required: false
          in: query
          description: Limit results to projects with IDs greater than the specified ID.
        - name: id_before
          schema:
            type: integer
          required: false
          in: query
          description: Limit results to projects with IDs less than the specified ID.
        - name: last_activity_after
          schema:
            type: string
            format: 'ISO 8601 YYYY-MM-DDTHH:MM:SSZ'
          required: false
          in: query
          description: Limit results to projects with last_activity after specified time.
        - name: last_activity_before
          schema:
            type: string
            format: 'ISO 8601 YYYY-MM-DDTHH:MM:SSZ'
          required: false
          in: query
          description: Limit results to projects with last_activity before specified time.
        - name: membership
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by projects that the current user is a member of.
        - name: min_access_level
          schema:
            type: integer
            enum:
              - 0
              - 5
              - 10
              - 20
              - 30
              - 40
              - 50
          required: false
          in: query
          description: Limit by current user minimal access level.
        - name: order_by
          schema:
            type: string
            default: created_at
            enum:
              - id
              - name
              - path
              - created_at
              - updated_at
              - last_activity_at
              - repository_size
              - storage_size
              - packages_size
              - wiki_size
          required: false
          in: query
          description: >-
            Return projects ordered by id, name, path, created_at, updated_at,
            or last_activity_at fields. repository_size, storage_size,
            packages_size or wiki_size fields are only allowed for admins.
            Default is created_at.
        - name: owned
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by projects explicitly owned by the current user.
        - name: repository_checksum_failed
          schema:
            type: boolean
          required: false
          in: query
          description: >-
            Limit projects where the repository checksum calculation has failed
            (Introduced in GitLab Premium 11.2).
        - name: repository_storage
          schema:
            type: string
            enum:
              - repository_storage
          required: false
          in: query
          description: >-
            Limit results to projects stored on repository_storage. (admins
            only)
        - name: search_namespaces
          schema:
            type: boolean
            default: false
          required: false
          in: query
          description: >-
            Include ancestor namespaces when matching search criteria. Default
            is false.
        - name: search
          schema:
            type: string
          required: false
          in: query
          description: Return list of projects matching the search criteria.
        - name: simple
          schema:
            type: boolean
          required: false
          in: query
          description: >-
            Return only limited fields for each project. This is a no-op without
            authentication as then only simple fields are returned.
        - name: sort
          schema:
            type: string
            enum:
              - asc
              - desc
            default: desc
          required: false
          in: query
          description: Return projects sorted in asc or desc order. Default is desc.
        - name: starred
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by projects starred by the current user.
        - name: statistics
          schema:
            type: boolean
          required: false
          in: query
          description: Include project statistics.
        - name: visibility
          schema:
            type: string
            enum:
              - public
              - internal
              - private
          required: false
          in: query
          description: 'Limit by visibility public, internal, or private.'
        - name: wiki_checksum_failed
          schema:
            type: boolean
          required: false
          in: query
          description: >-
            Limit projects where the wiki checksum calculation has failed
            (Introduced in GitLab Premium 11.2).
        - name: with_custom_attributes
          schema:
            type: boolean
          required: false
          in: query
          description: Include custom attributes in response. (admins only)
        - name: with_issues_enabled
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by enabled issues feature.
        - name: with_merge_requests_enabled
          schema:
            type: boolean
          required: false
          in: query
          description: Limit by enabled merge requests feature.
        - name: with_programming_language
          schema:
            type: string
          required: false
          in: query
          description: Limit by projects which use the given programming language.
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    description:
                      type: string
                    default_branch:
                      type: string
                    ssh_url_to_repo:
                      type: string
                    http_url_to_repo:
                      type: string
                    web_url:
                      type: string
                    readme_url:
                      type: string
                    tag_list:
                      type: array
                      items:
                        type: string
                    name:
                      type: string
                    name_with_namespace:
                      type: string
                    path:
                      type: string
                    path_with_namespace:
                      type: string
                    created_at:
                      type: string
                    last_activity_at:
                      type: string
                    forks_count:
                      type: integer
                    avatar_url:
                      type: string
                    star_count:
                      type: integer
